version: '2'
services:
  nemdevnis:
#    build: "nis"
    image: "rb2nem/nem-dev-guide:nis"
    volumes:
     - ${persistent_location}:/home/nem
  nemdevtools:
#    build: "tools"
    image: "rb2nem/nem-dev-guide:tools"
    image: "test"
    volumes:
     - ${tools_dir}:/home/nem/code
    ports:
     - "8081:8081"
     - "8082:8082"
     - "7778:7778"
     - "7890:7890"
